import { Header } from "@/components/Header";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";

const Legal = () => {
  return (
    <div className="min-h-screen bg-background">
      <Helmet>
        <title>Legal Notice — BMI-IMC.com</title>
        <meta name="description" content="Legal notice and terms of use for BMI-IMC.com, a free BMI calculator. Publisher information, intellectual property, privacy policy and disclaimer." />
        <meta name="robots" content="noindex, follow" />
        <link rel="canonical" href="https://bmi-imc.com/legal/" />
      </Helmet>
      <Header />

      <div className="container max-w-4xl py-12 px-4">
        <h1 className="text-4xl font-display font-bold mb-8">Legal Notice</h1>

        <div className="prose prose-gray max-w-none space-y-8 text-muted-foreground">

          <p>
            In accordance with applicable consumer protection and digital services legislation, the following
            legal notice is provided to users and visitors of the website bmi-imc.com. By accessing and
            browsing this website, users acknowledge and accept these terms in their entirety. This legal
            notice is accessible at all times via a link in the website footer.
          </p>

          <section>
            <h2 className="text-xl font-bold text-foreground">1. Publisher Information</h2>
            <p>
              The website bmi-imc.com is published by:<br />
              <strong>Mottalib Radif</strong><br />
              Email:{" "}
              <a href="mailto:contact@bmi-imc.com" className="text-primary hover:underline">
                contact@bmi-imc.com
              </a><br />
              Editor-in-Chief: Mottalib Radif
            </p>
            <p>
              The publisher assumes editorial responsibility for all content published on the website,
              with the exception of results generated by the BMI calculator, which depend on data entered
              by the user and on health parameters recognised by the World Health Organization (WHO) at
              the date of consultation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">2. Hosting</h2>
            <p>
              The website bmi-imc.com is hosted by:<br />
              <strong>GitHub Pages</strong> — GitHub, Inc.<br />
              88 Colin P Kelly Jr Street<br />
              San Francisco, CA 94107<br />
              United States<br />
              Website: https://pages.github.com
            </p>
            <p>
              GitHub Pages is a static website hosting service provided by GitHub, Inc., a subsidiary of
              Microsoft Corporation. The infrastructure relies on a global content delivery network (CDN)
              that serves pages from the server closest to each visitor to optimise loading times. GitHub
              Pages uses HTTPS to encrypt data in transit between the user's browser and the hosting
              servers. As a technical host, GitHub, Inc. does not exercise any editorial control over
              the website's content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">3. Purpose of the Website</h2>
            <p>
              BMI-IMC.com is a free online tool for calculating the Body Mass Index (BMI) according to
              the formula established by the World Health Organization (WHO). The site provides educational
              and informational content about BMI, weight management, and health in multiple languages.
              All tools and content are provided free of charge. The BMI calculator operates entirely
              client-side (in the user's browser) and no personal health data is transmitted to our servers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">4. Intellectual Property</h2>
            <p>
              All content on bmi-imc.com, including but not limited to text, graphics, logos, icons,
              images, audio clips, digital downloads, software, calculation algorithms, source code,
              page layouts and design elements, is the property of Mottalib Radif or its content
              suppliers and is protected by international copyright laws and intellectual property
              regulations. The compilation of all content on this site is the exclusive property of
              Mottalib Radif.
            </p>
            <p>
              You may not reproduce, distribute, display, sell, lease, transmit, create derivative works
              from, translate, modify, reverse-engineer, disassemble, decompile, or otherwise exploit
              this website or any portion of it unless expressly permitted by Mottalib Radif in writing.
              This prohibition includes reproduction of texts, copying of the calculator source code,
              substantial extraction of database content, and any form of scraping or automated content
              extraction.
            </p>
            <p>
              Users are authorised to browse the website and use the BMI calculator for strictly personal
              and private use. Any commercial use, systematic reproduction, or redistribution of content
              is prohibited without prior written consent. Brief quotations for informational purposes are
              permitted provided the source (bmi-imc.com) is credited and the quoted content is not
              distorted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">5. Medical Disclaimer</h2>
            <p>
              The information provided on BMI-IMC.com is for informational and educational purposes only.
              It does not constitute medical advice, diagnosis, or treatment. The BMI calculation results
              and health information presented on this website should not replace consultation with a
              qualified healthcare professional. Always seek the advice of your physician or other
              qualified health provider with any questions you may have regarding a medical condition.
            </p>
            <p>
              BMI is a screening tool and has known limitations. It does not distinguish between lean body
              mass and fat mass, and may not be appropriate for athletes, pregnant women, elderly
              individuals, or growing children. The publisher accepts no liability for any health decisions
              made based on information provided on this website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">6. Privacy Policy</h2>
            <p>
              BMI-IMC.com respects your privacy and is committed to protecting the personal data of its
              users in compliance with the General Data Protection Regulation (GDPR — Regulation EU
              2016/679) and all applicable data protection legislation.
            </p>
            <p>
              <strong>Health data:</strong> We do not collect, store, or transmit any personal health data
              entered into our BMI calculator. All calculations are performed locally in your web browser
              using JavaScript. No data (weight, height, age, gender) is sent to our servers or to third
              parties.
            </p>
            <p>
              <strong>Browsing data:</strong> We may use anonymised analytics tools to understand how
              visitors use our website. This data is aggregated and cannot be used to identify individual
              users. No profiling or advertising cookies are used.
            </p>
            <p>
              <strong>Third-party services:</strong> This website may load fonts from Google Fonts. By
              using this site, you consent to the processing of data by these services in accordance
              with their respective privacy policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">7. Cookie Policy</h2>
            <p>
              This website may use essential cookies strictly necessary for the proper functioning of the
              site. These technical cookies do not collect personal data and do not require prior consent
              under applicable legislation.
            </p>
            <p>
              No tracking, profiling, or advertising cookies are used on this website. User preferences
              (such as language selection or dark/light mode) are stored in the browser's localStorage,
              which is not a cookie and is never transmitted to our servers. You can configure your browser
              to refuse cookies or delete existing cookies at any time through your browser settings.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">8. Data Protection (GDPR)</h2>
            <p>
              In accordance with Articles 15 to 22 of the General Data Protection Regulation (GDPR),
              every user has the following rights regarding their personal data:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Right of access</strong> (Art. 15): obtain confirmation of whether personal data concerning you is being processed and, if so, obtain a copy of that data.</li>
              <li><strong>Right to rectification</strong> (Art. 16): obtain correction of inaccurate or incomplete personal data.</li>
              <li><strong>Right to erasure</strong> (Art. 17, "right to be forgotten"): obtain deletion of personal data when the conditions provided by law are met.</li>
              <li><strong>Right to restriction of processing</strong> (Art. 18): obtain restriction of processing in certain cases provided by law.</li>
              <li><strong>Right to data portability</strong> (Art. 20): receive personal data in a structured, commonly used and machine-readable format, and transmit it to another controller.</li>
              <li><strong>Right to object</strong> (Art. 21): object to processing of personal data on grounds relating to your particular situation.</li>
              <li><strong>Right to withdraw consent</strong> (Art. 7): withdraw consent at any time, without affecting the lawfulness of processing carried out before the withdrawal.</li>
            </ul>
            <p>
              Since the website does not collect personal data, these rights are currently not applicable
              in practice. However, for any request, clarification or exercise of the rights listed above,
              users may contact us at contact@bmi-imc.com. The publisher undertakes to respond within
              30 days, as required by Article 12 of the GDPR. Users also have the right to lodge a
              complaint with a supervisory authority.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">9. Terms of Use</h2>
            <p>
              By accessing bmi-imc.com, you agree to be bound by these terms and conditions. The website
              is accessible free of charge to any user with internet access. All costs incurred by the
              user to access the service (hardware, software, internet connection, etc.) are borne
              exclusively by the user.
            </p>
            <p>
              The publisher uses all reasonable means at its disposal to ensure quality access to the
              website but is under no obligation of result. Access to the website may be interrupted at
              any time for maintenance, updates or any other reason, without giving rise to any obligation
              or compensation.
            </p>
            <p>
              Users agree to use the website in accordance with its intended purpose and not to use it
              for unlawful purposes. Users are prohibited from attempting to breach the security of the
              website, using automated programs to access content in bulk, or reproducing the website in
              whole or in part without authorisation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">10. Limitation of Liability</h2>
            <p>
              BMI-IMC.com and its publisher shall not be liable for any direct, indirect, incidental,
              special, consequential, or punitive damages, including but not limited to loss of data,
              income, or profit, arising from or in connection with the use of this website or its content.
            </p>
            <p>
              While we strive to keep the information on this website accurate and up to date, we make
              no representations or warranties of any kind, express or implied, about the completeness,
              accuracy, reliability, suitability, or availability of the website or the information,
              products, services, or related graphics contained on the website for any purpose.
            </p>
            <p>
              The publisher also disclaims all liability in the event of service interruption, technical
              malfunction, data loss, or damage caused to the user's computer equipment as a result of
              browsing the website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">11. External Links</h2>
            <p>
              This website may contain links to external websites, including official health organisation
              websites (WHO, NHS, CDC). These links are provided for convenience and informational
              purposes only. We do not endorse and are not responsible for the content, privacy policies,
              or practices of third-party websites. Following any external link is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">12. Governing Law</h2>
            <p>
              This legal notice is governed by and construed in accordance with the laws of France. Any
              disputes arising from the use of this website shall be subject to the exclusive jurisdiction
              of the competent French courts, after any attempt at amicable resolution has failed. The
              potential invalidity of any clause of this notice shall not affect the validity of the
              remaining provisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">13. Changes to This Notice</h2>
            <p>
              The publisher reserves the right to modify this legal notice at any time to adapt it to
              legislative, regulatory or website changes. Changes take effect upon publication on this
              page. Users are encouraged to review this page periodically for updates. Use of the website
              after modification of this notice constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-foreground">14. Contact</h2>
            <p>
              For any questions regarding this legal notice, our privacy practices, or the operation of
              the website, please contact us at:{" "}
              <a href="mailto:contact@bmi-imc.com" className="text-primary hover:underline">
                contact@bmi-imc.com
              </a>
            </p>
          </section>

          <p className="text-sm italic">Last updated: June 2026</p>
        </div>

        <div className="border-t border-border pt-6 mt-10 flex flex-wrap gap-4 text-sm text-muted-foreground">
          <Link to="/" className="hover:text-primary">BMI Calculator</Link>
          <Link to="/about" className="hover:text-primary">About</Link>
          <Link to="/mentions-legales" className="hover:text-primary">Mentions Legales (FR)</Link>
        </div>
      </div>
    </div>
  );
};

export default Legal;
